# Generated by Django 2.1.14 on 2019-11-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191126_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='movie_name',
            field=models.CharField(max_length=255),
        ),
    ]
